### ISSUE TITLE
Add Documentation to Render Functions

### ISSUE THREAD

**Issue by ManuelTraub** [leonidk/fmb-plus#3]
Please add explanatory comments or documentation to the code within fm_render and zpfm_render. For instance, the function render_func_rays in fm_render appears to implement an optimized version of the two-parameter model described in the paper. However, without additional clarification, it becomes challenging to understand and subsequently reproduce."

**Comment by leonidk** [comment]
I think the code is the same as the paper, except for the caveat that weights behind the camera are set to zero, and there are small checks to avoid dividing by zero. 

But yes, I can add more documentation to the code. But if you found an inconsistency between the paper and the code, please let me know.

**Comment by leonidk** [comment]
@ManuelTraub commit 235a078 includes per-line comments for most of the render functions. Let me know if that's sufficient, or if you'd like more detail somewhere.
