### ISSUE TITLE
Linear approach explanation

### ISSUE THREAD

**Issue by maturk** [leonidk/fmb-plus#4]
Hey @leonidk, really interesting work! I am trying to understand your paper/implementation better, could you explain/derive how the "linear" approach is obtained from maximizing the Mahlanobis distance? 

![linear_approach](https://github.com/leonidk/fmb-plus/assets/30566358/9029f135-c243-4ba4-adce-b7a1d96174dd)

**Comment by leonidk** [comment]
Here's a derivation. I guess the paper is a little sloppy in that it assumes the rays start at the origin. But the more general version (and the one in the code) is this:

![image](https://github.com/leonidk/fmb-plus/assets/645763/c41fb8a2-11b9-4756-b6bd-439113c2e5eb)

As a careful note, this doesn't care about what the ray magnitude is. If you want traditional stereo/cartesian depth, you use rays where the z component is 1. If you want LIDAR distance, you use rays with magnitude 1.
